---
dist: trusty
version: ~> 1.0
env:
  - TF_VERSION=0.12.19
  - TF_URL="hashicorp-releases.yandexcloud.net"
  - TFLINT_VERSION=0.47.0
  - TF_INPUT=false
  - PACKER_VERSION=1.9.4
  - MACH_TYPE=linux_amd64
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2023-03/run.sh | bash
  - sudo apt-get update
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - sudo python get-pip.py
  - sudo pip install cryptography==2.2.2
  - sudo pip install ansible==2.6
  - sudo pip install ansible-lint==3.5.0
  - sudo apt-get install unzip git -y
  - curl -sLo /tmp/terraform.zip https://${TF_URL}/terraform/${TF_VERSION}/terraform_${TF_VERSION}_${MACH_TYPE}.zip
  - curl -sLo /tmp/packer.zip https://${TF_URL}/terraform/${PACKER_VERSION}/packer_${PACKER_VERSION}_${MACH_TYPE}.zip
  - curl -sLo /tmp/tflint.zip https://github.com/terraform-linters/tflint/releases/download/v${ftlint_version}/tflint_${MACH_TYPE}.zip
  - mkdir ~/bin
  - unzip /tmp/terraform.zip -d ~/bin
  - unzip /tmp/packer.zip -d ~/bin
  - unzip /tmp/tflint.zip -d ~/bin
  - chmod +x ~/bin/{terraform,packer,tflint}
  - export PATH="~/bin:$PATH"
  - tflint -v
  - terraform --version
  - packer --version
  - ansible-lint --version
script:
  - terraform validate ./terraform/prod
  - tflint --var-file=terraform.tfvars --minimum-failure-severity=error --chdir=terraform/prod/
  - terraform validate ./terraform/stage
  - tflint --var-file=terraform.tfvars --minimum-failure-severity=error --chdir=terraform/stage/
  - packer validate -var-file=packer/variables.json packer/app.json
  - packer validate -var-file=packer/variables.json packer/db.json
  - cd ansible
  - ansible-lint playbooks/deploy.yml
  - ansible-lint playbooks/clone.yml
  - ansible-lint playbooks/db.yml
  - ansible-lint playbooks/packer_*.yml
  - ansible-lint playbooks/users.yml
  - ansible-galaxy install -r environments/stage/requirements.yml
  - ansible-lint playbooks/app.yml --exclude=roles/jdauphant.nginx
  - ansible-lint playbooks/site.yml --exclude=roles/jdauphant.nginx
notifications:
  email:
    on_success: change
    on_failure: always
