packer {
  required_plugins {
    ansible = {
      source  = "github.com/hashicorp/ansible"
      version = "~> 1"
    }
  }
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "yandex" "autogenerated_1" {
  folder_id                = "${var.folder_id}"
  image_family             = "reddit-base"
  image_name               = "reddit-app-${local.timestamp}"
  instance_cores           = "2"
  max_retries              = "5"
  platform_id              = "${var.platform_id}"
  service_account_key_file = "${var.key_file}"
  source_image_family      = "ubuntu-1604-lts"
  ssh_username             = "${var.ssh_user}"
  use_internal_ip          = "false"
  use_ipv4_nat             = "true"
  zone                     = "ru-central1-a"
}

build {
  sources = ["source.yandex.autogenerated_1"]

  provisioner "ansible" {
    ansible_env_vars = ["ANSIBLE_CONFIG=ansible/ansible.cfg", "ANSIBLE_PIPELINING=true"]
    extra_arguments  = ["-vv", "--ssh-extra-args", "-o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa"]
    playbook_file    = "ansible/playbooks/packer_app.yml"
    user             = "${var.ssh_user}"
  }

}
