---
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"
- name: Get Service Status
  service_facts:
    services:
      name: puma
  register: service_status
  ignore_errors: true
- name: Display Service Status
  debug:
    var: service_status
- name: Add config for DB connection
  template:
    src: db.conf.j2
    dest: /home/ubuntu/db_config
    owner: ubuntu
    mode: "0644"
- name: Enable puma
  become: true
  systemd:
    enabled: true
    name: puma
  notify: Reload puma
