- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    owner: "{{ deploy_user }}"

- name: Fetch the latest version of application code
  git:
    repo: 'https://github.com/express42/reddit.git'
    dest: /home/{{ deploy_user }}/reddit
    force: true
    version: monolith

- name: Change ownership of a directory
  ansible.builtin.file:
    path: /home/{{ deploy_user }}/reddit
    state: directory
    recurse: true
    owner: "{{ deploy_user }}"

- name: Bundle install app
  bundler:
    state: present
    chdir: /home/{{ deploy_user }}/reddit

- name: Add unit file for Puma
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
    mode: 644
  notify:
    - Reload systemd
    - Restart puma
