---
- name: Add APT repository
  apt_repository:
    repo: "ppa:rael-gc/rvm"
    state: present

- name: Update and upgrade apt packages
  apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 86400

- name: Install ruby and rubygems
  apt: "name={{ item }} state=present"
  with_items:
    - build-essential
    - dialog
    - rsync
    - dos2unix
    - git
    - telnet
    - ruby-full
    - ruby-bundler
  tags: ruby

- name: Install gem bundler
  gem:
    name: bundler
    norc: false
    state: present
    user_install: false
    force: true
    version: 2.3.26
  become: true
  tags: ruby
