---
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"
- name: Fetch the latest version of application code
  git:
    repo: 'https://github.com/express42/reddit.git'
    dest: /home/ubuntu/reddit
    version: monolith
  notify: Start puma
- name: Bundle install
  bundler:
    state: present
    chdir: /home/ubuntu/reddit
- name: Add unit file for Puma
  become: true
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
    mode: "0644"
  notify: Start puma
