all:
  hosts:
    reddit-app:
  children:
    app:
      hosts:
        reddit-app:
          ansible_host: 130.193.39.225
      vars:
         ansible_port: 22
    db:
      hosts:
        reddit-db:
          ansible_host: 158.160.54.176
